# Setup
title:               Annular Eclipse
tagline:             '달이 거짓말처럼 태양에 겹친 날'
description:         '달이 거짓말처럼 태양에 겹친 날'
url:                 https://gayuna.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Gayuna
  url:               https://github.com/gayuna
  email:             gayoun0712@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             #0.0.1
google_analytics_id: #UA-XXXX-Y
